import Head from 'next/head'

import { LayoutHeader, LayoutFooter, LayoutHome } from '@components/layout'

export default function Home() {
	return (
		<div>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<LayoutHeader />

			<LayoutHome />

			<LayoutFooter />
			<LayoutFooter alternate="true" />
		</div>
	)
}
